### PR TITLE
Hammerfix

### PR DESCRIPTION
**Pull request by dbavatar**
This fixes some unintentional slowdowns with the previous commits.

### CODE REVIEW

**Comment by dnewman-polar3d** [comment]
Owing to unforseen events, I've been unable to try these out as of yet.  It'll be a couple of weeks until I can as I'll be out of town.  However, I am still anxious to give them a work out and appreciate your contributions!

**Comment by dcnewman** [comment]
Owing to unforseen events, I've been unable to try these changes out.  And, I'm going to be travelling over the next couple of weeks.  However, I am anxious to try them out and appreciate your work and contributions.

**Comment by dbavatar** [comment]
I think I've actually discovered that the handling of feed rate is not correct in this patch, it can set it where it was zero before. Please don't pull this into master, I will resubmit after more work.

**Comment by caall99** [comment]
Awwww... I am patiently sitting on the sideline, waiting in ignorance. Thanks for your hard work!

**Pull request closed without merging**
