### PR TITLE
Hammerfix

### PR DESCRIPTION
**Pull request by dbavatar**
I believe this is a good set of changes. The biggest fix here is the calculation of final_speed, which was quite wrong before. I think any new work on the planner must be based on this fn, so it's good for everyone to have it now.

### CODE REVIEW

**Comment by dcnewman** [comment]
I'll be traveling back home on Wednesday.  I hope to be able to try these on the weekend after I get my family out the door on a trip they are taking without me for a week.

A quick look at them suggests that they will indeed prove beneficial and interesting.

Thanks

**Comment by caall99** [comment]
I really do hope you get around to it, as its probably Sailfish's most glaring issue. The community would be very thankful! For many months this exact symptom has been driving me completely insane... Dan would remind me about Sailfish's inability to plan centripetal acceleration, and I would continue reducing my acceleration, print speed, and max speed change settings to rectify the problem. As you noticed, making these changes never resolved the issue. I too am experiencing hammering at every last segment in a chain of segments. I tried printing the lighthouse model here: http://www.thingiverse.com/thing:1379330

The motion while printing outlines was painful to watch, and I would frequently see the nozzle overshoot plastic beyond the models perimeter. Ultimately the surface finish was inadequate. On the other hand, on simple cubic and flat faced models, I have no problem printing with very high quality. If only organic surfaces could be printing with similar accuracy and fluidity.

**Comment by dcnewman** [comment]
Thanks much.  Will try this week.

**Comment by dcnewman** [comment]
With the avr gcc 4.6.2/.3 toolchain, _MemoryBarrier() is incorrectly defined in cpufunc.h.  It's declared as

    #define _MemoryBarrier() __asm__ __volatile__(:::"memory")

while it should be

    #define _MemoryBarrier() __asm__ __volatile__("":::"memory")

The former tosses an error at compile time.  But that means that in order for folks using the condoned toolchain, _MemoryBarrier() needs to be defined in Command.cc and not using avr/cpufunc.h.  Hence a checkin I will be doing in a day or two.

Unfortunately, something has perturbed the virtual function tables and now I'm getting the dreaded `(.ctors+0x0): warning: internal error: out of range error` because a vtable is crossing a boundary it shouldn't.  I do know a couple of ways of dealing with it include a gcc switch that sometimes works.

**Comment by dbavatar** [comment]
I've been building on 4.9.2, FWIW haven't seen a problem with it yet.

**Comment by caall99** [comment]
dbavatar, I am still learning my way around GitHub. Looks like Dan merged your hammerfix into his master. I would like to build a new copy of Sailfish with your hammerfix, pipeline SD card reads, and whatever other improvements you have made. My current firmware is built on this source: https://github.com/dbavatar/Sailfish-MightyBoardFirmware/commit/9b746bac6b2a85f2f9f5b4cef2a26a6c09b70dbb

I cannot tell whether Dan's master has all those other improvements in it (because I am a GitHub noob). I assume not, since he hasn't merged them? Could you link me to the firmware source that you are currently having success with, which includes the aforementioned improvements? Thanks!

**Comment by dcnewman** [comment]
On 12/09/2016 4:12 PM, caall99 wrote:
> dbavatar, I am still learning my way around GitHub. Looks like Dan merged your hammerfix into his master. I would like to build a new copy of Sailfish with your hammerfix, pipeline SD card reads, and whatever other improvements you have made. My current firmware is built on this source: dbavatar@9b746ba <https://github.com/dbavatar/Sailfish-MightyBoardFirmware/commit/9b746bac6b2a85f2f9f5b4cef2a26a6c09b70dbb>
>
> I cannot tell whether Dan's master has all those other improvements in it (because I am a GitHub noob). I assume not, since he hasn't merged them? Could you link me to the firmware source that you are currently having success with, which includes the aforementioned improvements? Thanks!

I've merged them all in.

Dan

**Pull request merged**
